---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: capstone
  name: developer-role
rules: 
- apiGroups: ["", "extensions", "apps"]
  resources: ["pods"]
  verbs: ["create","update","delete","get","list"]